# Documented at https://docs.coderabbit.ai/guides/configure-coderabbit
language: "en-US"
early_access: true
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: false
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - packages/account_sdk/src/abigen/*
chat:
  auto_reply: true
